name: Build AlNajm Multi-OS
on: [push]
jobs:
  # بناء نسخة الويندوز
  windows-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Deps
        run: sudo apt-get update && sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git g++-mingw-w64-x86-64 python3
      - name: Build Windows
        run: |
          cd depends && make HOST=x86_64-w64-mingw32 -j2
          cd .. && ./autogen.sh && ./configure --prefix=`pwd`/depends/x86_64-w64-mingw32 && make -j2
      - name: Upload Windows
        uses: actions/upload-artifact@v4
        with:
          name: AlNajm-Windows
          path: src/qt/*.exe

  # بناء نسخة الأندرويد (تشتغل داخل Termux)
  android-termux-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Deps
        run: sudo apt-get update && sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git python3
      - name: Build for Termux (ARM64)
        run: |
          ./autogen.sh
          ./configure --enable-static --disable-shared --with-gui=no
          make -j2
      - name: Upload Android-Termux
        uses: actions/upload-artifact@v4
        with:
          name: AlNajm-Android-Termux
          path: src/alnajmd
