name: AlNajm-Super-Build-System
on: [push]
jobs:
  build-windows:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Install Toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git g++-mingw-w64-x86-64 libssl-dev libevent-dev libboost-all-dev
    - name: Build BDB
      run: |
        BDB_PREFIX="${{ github.workspace }}/db4"
        mkdir -p "$BDB_PREFIX"
        curl -L 'https://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz' -o db.tar.gz
        tar -xzf db.tar.gz
        cd db-4.8.30.NC/build_unix/
        ../dist/configure --enable-cxx --disable-shared --with-pic --prefix="$BDB_PREFIX" --host=x86_64-w64-mingw32
        make install -j$(nproc)
    - name: Build Windows
      run: |
        BDB_PREFIX="${{ github.workspace }}/db4"
        chmod +x autogen.sh
        ./autogen.sh
        ./configure --host=x86_64-w64-mingw32 --enable-static --disable-shared --without-gui --with-incompatible-bdb CPPFLAGS="-I${BDB_PREFIX}/include" LDFLAGS="-L${BDB_PREFIX}/lib"
        make -j$(nproc)
    - name: Upload Windows
      uses: actions/upload-artifact@v4
      with:
        name: AlNajm-Windows
        path: src/*.exe

  build-android-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Linux/Android Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git libssl-dev libevent-dev libboost-all-dev libdb++-dev
    - name: Build Android-Compatible Core
      run: |
        chmod +x autogen.sh
        ./autogen.sh
        ./configure --enable-static --disable-shared --without-gui --with-incompatible-bdb
        make -j$(nproc)
    - name: Upload Android-Core
      uses: actions/upload-artifact@v4
      with:
        name: AlNajm-Android-Linux-Core
        path: src/alnajmd
