name: AlNajm-HighPower-Build
on: [push]
jobs:
  build:
    # استخدام Ubuntu-20.04 لأنه يوفر 4 أنوية و 16 جيجا رام مجاناً للمشاريع العامة
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v4

    - name: Set Up OS Resources
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git g++-mingw-w64-x86-64 libssl-dev libevent-dev libboost-all-dev

    - name: Build Core Components (Multi-Threaded)
      run: |
        BDB_PREFIX="${{ github.workspace }}/db4"
        mkdir -p "$BDB_PREFIX"
        curl -L 'https://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz' -o db.tar.gz
        tar -xzf db.tar.gz
        cd db-4.8.30.NC/dbinc
        sed -i 's/__atomic_compare_exchange/__atomic_compare_exchange_db/g' atomic.h
        cd ../build_unix/
        ../dist/configure --enable-cxx --disable-shared --with-pic --prefix="$BDB_PREFIX"
        # استخدام nproc لاستغلال الـ 4 أنوية كاملة كما ذكرت الوثيقة
        make install -j$(nproc)

    - name: Compile AlNajm Wallet
      run: |
        BDB_PREFIX="${{ github.workspace }}/db4"
        chmod +x autogen.sh
        ./autogen.sh
        ./configure --host=x86_64-w64-mingw32 --enable-static --disable-shared --without-gui --with-incompatible-bdb CPPFLAGS="-I${BDB_PREFIX}/include" LDFLAGS="-L${BDB_PREFIX}/lib"
        # استغلال كامل قوة الجهاز الافتراضي
        make -j$(nproc)

    - name: Save & Upload
      uses: actions/upload-artifact@v4
      with:
        name: AlNajm-Windows-64bit
        path: src/*.exe
        retention-days: 1
